# Generated by Django 4.0.4 on 2022-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('new_student_img', models.ImageField(blank=True, null=True, upload_to='Features/training_data')),
            ],
        ),
    ]
