# Generated by Django 4.0.4 on 2022-05-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0004_alter_newstudent_new_student_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewStudent',
        ),
    ]
