# Generated by Django 4.0.4 on 2022-05-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Features', '0005_delete_newstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='newStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
